### ISSUE TITLE
An error occured! Please check your internet connection.

### ISSUE THREAD

**Issue by xanestus** [ppy/osu-stable-issues#1004]
I recently had to build a new PC (Windows 10, 64-bit) and every time I try to install osu, the installer opens and immediately gives me this error message. This is what pops up in the update logs:

2022-06-30T06:09:23: CallbackStatus updated to Checking
2022-06-30T06:09:23: 
2022-06-30T06:09:23: Beginning update thread
2022-06-30T06:09:23: Stream: Stable40
2022-06-30T06:09:23: 
2022-06-30T06:09:23: Running cleanup..
2022-06-30T06:09:23: Cleanup successful!
2022-06-30T06:09:23: Requesting update information...
2022-06-30T06:09:23: System.TypeInitializationException: The type initializer for '#=z$c6$mfxoJsah$iImsZI5m2o=' threw an exception. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: The type initializer for 'System.MarvinHash' threw an exception. (C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\machine.config) ---> System.TypeInitializationException: The type initializer for 'System.MarvinHash' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.Cryptography.CryptographicException: Provider type not defined.
2022-06-30T06:09:23: 
2022-06-30T06:09:23: at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
2022-06-30T06:09:23: at System.Security.Cryptography.Utils._AcquireCSP(CspParameters param, SafeProvHandle& hProv)
2022-06-30T06:09:23: at System.Security.Cryptography.Utils.AcquireProvHandle(CspParameters parameters)
2022-06-30T06:09:23: at System.Security.Cryptography.Utils.get_StaticProvHandle()
2022-06-30T06:09:23: at System.Security.Cryptography.RNGCryptoServiceProvider..ctor()
2022-06-30T06:09:23: --- End of inner exception stack trace ---
2022-06-30T06:09:23: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2022-06-30T06:09:23: at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2022-06-30T06:09:23: at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
2022-06-30T06:09:23: at System.Security.Cryptography.RandomNumberGenerator.Create()
2022-06-30T06:09:23: at System.MarvinHash.GenerateSeed()
2022-06-30T06:09:23: at System.MarvinHash..cctor()
2022-06-30T06:09:23: --- End of inner exception stack trace ---
2022-06-30T06:09:23: at System.Xml.NameTable..ctor()
2022-06-30T06:09:23: at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
2022-06-30T06:09:23: at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
2022-06-30T06:09:23: --- End of inner exception stack trace ---
2022-06-30T06:09:23: at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
2022-06-30T06:09:23: at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
2022-06-30T06:09:23: at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
2022-06-30T06:09:23: at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
2022-06-30T06:09:23: --- End of inner exception stack trace ---
2022-06-30T06:09:23: at System.Configuration.ConfigurationManager.PrepareConfigSystem()
2022-06-30T06:09:23: at System.Configuration.ConfigurationManager.GetSection(String sectionName)
2022-06-30T06:09:23: at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
2022-06-30T06:09:23: at System.Net.Configuration.SettingsSectionInternal.get_Section()
2022-06-30T06:09:23: at System.Net.ServicePointManager.set_Expect100Continue(Boolean value)
2022-06-30T06:09:23: at #=z$c6$mfxoJsah$iImsZI5m2o=..cctor()
2022-06-30T06:09:23: --- End of inner exception stack trace ---
2022-06-30T06:09:23: at #=z$c6$mfxoJsah$iImsZI5m2o=..ctor(String #=zqQPBLtg=, Object[] #=zbBQcgTM=)
2022-06-30T06:09:23: at #=zambcVHyub25Nys_SZ5q1CnPShjV2..ctor(String #=zqQPBLtg=, Object[] #=zbBQcgTM=)
2022-06-30T06:09:23: at #=zmSa_BhR6PihG1ezYOTSMXaQ=.#=zoJ7U0pc=()
2022-06-30T06:09:23: 
2022-06-30T06:09:23: Saving out global config
2022-06-30T06:09:23: 
2022-06-30T06:09:23: Ending update thread with result: Error
2022-06-30T06:09:23: 
2022-06-30T06:09:23: CallbackStatus updated to Error
2022-06-30T06:09:23: Running cleanup..
2022-06-30T06:09:23: Cleanup successful!
2022-06-30T06:09:23: Resetting update process
2022-06-30T06:09:23: Disabling threaded downloads

2022-06-30T06:09:28: CallbackStatus updated to Checking
2022-06-30T06:09:28: 
2022-06-30T06:09:28: Beginning update thread
2022-06-30T06:09:28: Stream: Stable40
2022-06-30T06:09:28: 
2022-06-30T06:09:28: Running cleanup..
2022-06-30T06:09:28: Cleanup successful!
2022-06-30T06:09:28: Requesting update information...
2022-06-30T06:09:28: System.TypeInitializationException: The type initializer for '#=z$c6$mfxoJsah$iImsZI5m2o=' threw an exception. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: The type initializer for 'System.MarvinHash' threw an exception. (C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\machine.config) ---> System.TypeInitializationException: The type initializer for 'System.MarvinHash' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.Cryptography.CryptographicException: Provider type not defined.
2022-06-30T06:09:28: 
2022-06-30T06:09:28: at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
2022-06-30T06:09:28: at System.Security.Cryptography.Utils._AcquireCSP(CspParameters param, SafeProvHandle& hProv)
2022-06-30T06:09:28: at System.Security.Cryptography.Utils.AcquireProvHandle(CspParameters parameters)
2022-06-30T06:09:28: at System.Security.Cryptography.Utils.get_StaticProvHandle()
2022-06-30T06:09:28: at System.Security.Cryptography.RNGCryptoServiceProvider..ctor()
2022-06-30T06:09:28: --- End of inner exception stack trace ---
2022-06-30T06:09:28: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2022-06-30T06:09:28: at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2022-06-30T06:09:28: at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
2022-06-30T06:09:28: at System.Security.Cryptography.RandomNumberGenerator.Create()
2022-06-30T06:09:28: at System.MarvinHash.GenerateSeed()
2022-06-30T06:09:28: at System.MarvinHash..cctor()
2022-06-30T06:09:28: --- End of inner exception stack trace ---
2022-06-30T06:09:28: at System.Xml.NameTable..ctor()
2022-06-30T06:09:28: at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
2022-06-30T06:09:28: at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
2022-06-30T06:09:28: --- End of inner exception stack trace ---
2022-06-30T06:09:28: at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
2022-06-30T06:09:28: at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
2022-06-30T06:09:28: at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
2022-06-30T06:09:28: at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
2022-06-30T06:09:28: --- End of inner exception stack trace ---
2022-06-30T06:09:28: at System.Configuration.ConfigurationManager.PrepareConfigSystem()
2022-06-30T06:09:28: at System.Configuration.ConfigurationManager.GetSection(String sectionName)
2022-06-30T06:09:28: at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
2022-06-30T06:09:28: at System.Net.Configuration.SettingsSectionInternal.get_Section()
2022-06-30T06:09:28: at System.Net.ServicePointManager.set_Expect100Continue(Boolean value)
2022-06-30T06:09:28: at #=z$c6$mfxoJsah$iImsZI5m2o=..cctor()
2022-06-30T06:09:28: --- End of inner exception stack trace ---
2022-06-30T06:09:28: at #=z$c6$mfxoJsah$iImsZI5m2o=..ctor(String #=zqQPBLtg=, Object[] #=zbBQcgTM=)
2022-06-30T06:09:28: at #=zambcVHyub25Nys_SZ5q1CnPShjV2..ctor(String #=zqQPBLtg=, Object[] #=zbBQcgTM=)
2022-06-30T06:09:28: at #=zmSa_BhR6PihG1ezYOTSMXaQ=.#=zoJ7U0pc=()
2022-06-30T06:09:28: 
2022-06-30T06:09:28: Saving out global config
2022-06-30T06:09:28: 
2022-06-30T06:09:28: Ending update thread with result: Error
2022-06-30T06:09:28: 
2022-06-30T06:09:28: CallbackStatus updated to Error
2022-06-30T06:09:28: Running cleanup..
2022-06-30T06:09:28: Cleanup successful!
2022-06-30T06:09:28: Resetting update process

I'm not code savvy so none of this means anything to me except something is wrong. I've already tried disabling firewalls and toggling TLS 1.0, 1.1, and 1.2 with no luck.

**Comment by peppy** [comment]
Your windows installation is corrupt. Please consult google with the error message and you should find tens or hundreds of results.
