### ISSUE TITLE
Osu crashed pop up

### ISSUE THREAD

**Issue by Fatman1905** [ppy/osu-stable-issues#1099]
My game is crashed everytime i open it :(
It ran normally last day

OpenTK.Graphics.GraphicsModeException: Failed to retrieve GraphicsMode, no fitting configurations, error SUCCESS
at OpenTK.Platform.Egl.EglGraphicsMode.SelectGraphicsMode(SurfaceType surface_type, IntPtr display, ColorFormat color, Int32 depth, Int32 stencil, Int32 samples, ColorFormat accum, Int32 buffers, Boolean stereo, RenderableFlags renderable_flags, Boolean fullscreen)
at OpenTK.Platform.Egl.EglGraphicsMode.SelectGraphicsMode(SurfaceType surface_type, IntPtr display, ColorFormat color, Int32 depth, Int32 stencil, Int32 samples, ColorFormat accum, Int32 buffers, Boolean stereo, RenderableFlags renderable_flags, Boolean fullscreen)
at OpenTK.Platform.Egl.EglContext..ctor(GraphicsMode mode, EglWindowInfo window, IGraphicsContext sharedContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
at OpenTK.Platform.Egl.EglAnglePlatformFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
at #=zhMCkeurgT7hd5U9RuJdHh64pwnFq.#=ztPjLru4=(Int32 #=zMHqjJSk=, Int32 #=zHKEDTs0=, GraphicsContextFlags #=z0vE1WYA=)
at #=z9ylEVZ5aFRDkEr$ilV8l1dA=.OnHandleCreated(EventArgs #=z9MdZqgg=)
at #=znUYpLA7X$NsSvjgmoGN1z3h8W7Ot.OnHandleCreated(EventArgs #=z9MdZqgg=)
at System.Windows.Forms.Control.WmCreate(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
at System.Windows.Forms.Form.WmCreate(Message& m)
at System.Windows.Forms.Form.WndProc(Message& m)
at #=zFmfyb7VtW3XK4lAipoJwiY0=.WndProc(Message& #=zM1u2yFw=)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by smoogipoo** [comment]
Try holding `Shift` while starting osu! until a window pops up, and click the checkbox to enable/disable "Compatibility Mode".
