### ISSUE TITLE
Several crashes during multi map start

### ISSUE THREAD

**Issue by arcutright** [ppy/osu-stable-issues#1228]
Hard crashes that I can't reproduce reliably
- all crashes happened in multi when it transitioned from in lobby -> playing
- maybe only happened with maps that have storyboards / videos, and I always have both enabled

Here are some unique crashes from event viewer -> net framework logs. I have lots of duplicate entries with the same stack trace, but these are uniques from the lot (for a 1 month period).

Top few are from cutting edge, the rest were from stable. All from feb 9 - mar 7, most recent on top.

```
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at dje_zZNFS88EDS6TBK7UH989AYWMPCZNCGL85572TL8GE8KVXVMZ_ejd.#=z98MrTq0W1zDjSXCVlg==(IntPtr ByRef, System.String, IntPtr, Int32, IntPtr)
   at #=zAY6J$KdFmWiEcIIvl8topdqkarn3_ofa1w==.#=z42xIesE=(Byte[])
   at #=zV0M_ziMdLUXM5yNEptp0UKJC_QqarIJkBA==..ctor(System.String, #=zX9ZsHupyFGUV$BjhK47qFobf3ZEKT_hB8g==, #=z9t7gR3iVlqrWDKdLP3gRtzd379Ngs1TEmQ==)
   at #=zNbFSGtUF_5GigMiT1$vAoLYRC7xm..ctor(System.String, #=zX9ZsHupyFGUV$BjhK47qFobf3ZEKT_hB8g==, #=z9t7gR3iVlqrWDKdLP3gRtzd379Ngs1TEmQ==, Int32)
   at #=z9bv9Kw6RxJEdI3s3RiibGSfg1vO5.#=znrTgF5s=(System.String, Int32)
   at #=zKYGxjn3yvAYV6YCiFcqYgbdb7df4.#=zJ4dPFjE=(osu.GameplayElements.FileSection, Boolean, Boolean, Boolean)
   at #=zKYGxjn3yvAYV6YCiFcqYgbdb7df4.#=zpv_GjmA=(Boolean, Boolean)
   at #=zRFXeQAYOjclG7SVDLvlWndJqtIlB.#=zKxtYMoYfX6Df()
   at #=ztqC_8LvRJ1oq6lLn_uxcc3b64Whm.#=zKxtYMoYfX6Df()
   at #=zzlKvSPmpKXfpq37_Gujn4Cg=.#=z53I$aV0=()
   at #=zKipbVKjc2W_6lzwsBQ==+#=zXA$wwAGcmflQfXCILgpyspo=.#=zYA6EQ06mOkf2PkNWpQL2PXg=()
   at #=z3IhEB07LZFJVBGKaAEJUVRcxGYmZ+#=z9m5LMsoXUiDokt1JpDPEFvk=.#=znSeIvTvK5PJ4Oei8EQ==(System.Object)
   at #=zBAcoXUPd3tKl9CrL$sMiUVM=.#=zrDar4LYMKtuV()
   at #=zBAcoXUPd3tKl9CrL$sMiUVM=.#=zeVb7lLQ=()
   at #=zkORhci0QCWUBiaOzU7kvRWI=.#=zrDar4LYMKtuV(#=zBAcoXUPd3tKl9CrL$sMiUVM=)
   at #=zkORhci0QCWUBiaOzU7kvRWI=.#=zoSSaDX63beXS()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at dje_zZNFS88EDS6TBK7UH989AYWMPCZNCGL85572TL8GE8KVXVMZ_ejd.#=zd_epjWEZAeB622bSKA==(IntPtr)
   at #=zAY6J$KdFmWiEcIIvl8topdqkarn3_ofa1w==.#=zrkeWDFE=(Boolean)
   at #=zAY6J$KdFmWiEcIIvl8topdqkarn3_ofa1w==.Finalize()

Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at dje_zHH9KHUTQWA8Z92ZUTJCVQWPHE8LRHZQKL6WDGUB2CNDLCBZ_ejd.#=zr1WZeqLFhu9tWa6OCA==(IntPtr ByRef, System.String, IntPtr, Int32, IntPtr)
   at #=z4UN2rHjc_9fswkZz08YC6QokVjYbK6Q$$w==.#=zvKGo1WY=(Byte[])
   at #=zhFJzpeoQPg1homJOevNJ70apjJPMagJ09g==..ctor(System.String, #=zDCx7WCAxQt4zIxr0ibTVuonjJZjEwIGo6w==, #=z2R8CsTomgs_midIpyP5SBPeSTN9pFVVL4Q==)
   at #=zm9mQijqoVhk2In9O0DveieXpssGf..ctor(System.String, #=zDCx7WCAxQt4zIxr0ibTVuonjJZjEwIGo6w==, #=z2R8CsTomgs_midIpyP5SBPeSTN9pFVVL4Q==, Int32)
   at #=znINX42Iv3pCiG8uEFtziIYxvZLVm.#=zJdXS36o=(System.String, Int32)
   at #=zR4i2Ic_If9$d8sK6ZWKGSUppo9An.#=zEXHD9X8=(osu.GameplayElements.FileSection, Boolean, Boolean, Boolean)
   at #=zR4i2Ic_If9$d8sK6ZWKGSUppo9An.#=z8PWAC88=(Boolean, Boolean)
   at #=zOTWUr4vq60U15SRmD_JItyatbhdR.#=z4e1YFegF3yy6()
   at #=zixFcxZggh8tYtU28mVn1h5E=.#=z6qvLZdk=()
   at #=zduF3QmjgMG4eSc$fOQ==+#=zufsho7e5Ry$kF5EYIJ4$S4A=.#=zBDpj$2oc0s2sOAftxJKCKrk=()
   at #=zLZaJw5TIvwRRqn3n4R0k6wr7yj8y+#=zZzxcgetLynk3PeWwExaPhLU=.#=z81MhV8VZmhG94ppe$w==(System.Object)
   at #=z$YxN9u_fyQI3hk4$s5iZMi4=.#=ztWDIBDHgod98()
   at #=z$YxN9u_fyQI3hk4$s5iZMi4=.#=zVqyGBtA=()
   at #=zGAyCIGPhJVoKMmUVcwlrBy4=.#=ztWDIBDHgod98(#=z$YxN9u_fyQI3hk4$s5iZMi4=)
   at #=zGAyCIGPhJVoKMmUVcwlrBy4=.#=zHbhA3WPn5MaX()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at dje_zHH9KHUTQWA8Z92ZUTJCVQWPHE8LRHZQKL6WDGUB2CNDLCBZ_ejd.#=zGA1hXVHyGqZm3xpr1A==(IntPtr)
   at #=z4UN2rHjc_9fswkZz08YC6QokVjYbK6Q$$w==.#=zWiEmPiE=(Boolean)
   at #=zhFJzpeoQPg1homJOevNJ70apjJPMagJ09g==.#=zWiEmPiE=(Boolean)
   at #=zhFJzpeoQPg1homJOevNJ70apjJPMagJ09g==.Finalize()

Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at dje_zHH9KHUTQWA8Z92ZUTJCVQWPHE8LRHZQKL6WDGUB2CNDLCBZ_ejd.#=zr1WZeqLFhu9tWa6OCA==(IntPtr ByRef, System.String, IntPtr, Int32, IntPtr)
   at #=z4UN2rHjc_9fswkZz08YC6QokVjYbK6Q$$w==.#=zvKGo1WY=(Byte[])
   at #=zhFJzpeoQPg1homJOevNJ70apjJPMagJ09g==..ctor(System.String, #=zDCx7WCAxQt4zIxr0ibTVuonjJZjEwIGo6w==, #=z2R8CsTomgs_midIpyP5SBPeSTN9pFVVL4Q==)
   at #=zm9mQijqoVhk2In9O0DveieXpssGf..ctor(System.String, #=zDCx7WCAxQt4zIxr0ibTVuonjJZjEwIGo6w==, #=z2R8CsTomgs_midIpyP5SBPeSTN9pFVVL4Q==, Int32)
   at #=znINX42Iv3pCiG8uEFtziIYxvZLVm.#=zJdXS36o=(System.String, Int32)
   at #=zR4i2Ic_If9$d8sK6ZWKGSUppo9An.#=zEXHD9X8=(osu.GameplayElements.FileSection, Boolean, Boolean, Boolean)
   at #=zR4i2Ic_If9$d8sK6ZWKGSUppo9An.#=z8PWAC88=(Boolean, Boolean)
   at #=zOTWUr4vq60U15SRmD_JItyatbhdR.#=z4e1YFegF3yy6()
   at #=zAN3Q8xtpDq01zRMYq2CI$mxxPXYE.#=z4e1YFegF3yy6()
   at #=zixFcxZggh8tYtU28mVn1h5E=.#=z6qvLZdk=()
   at #=zduF3QmjgMG4eSc$fOQ==+#=zufsho7e5Ry$kF5EYIJ4$S4A=.#=zBDpj$2oc0s2sOAftxJKCKrk=()
   at #=zLZaJw5TIvwRRqn3n4R0k6wr7yj8y+#=zZzxcgetLynk3PeWwExaPhLU=.#=z81MhV8VZmhG94ppe$w==(System.Object)
   at #=z$YxN9u_fyQI3hk4$s5iZMi4=.#=ztWDIBDHgod98()
   at #=z$YxN9u_fyQI3hk4$s5iZMi4=.#=zVqyGBtA=()
   at #=zGAyCIGPhJVoKMmUVcwlrBy4=.#=ztWDIBDHgod98(#=z$YxN9u_fyQI3hk4$s5iZMi4=)
   at #=zGAyCIGPhJVoKMmUVcwlrBy4=.#=zHbhA3WPn5MaX()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at dje_zHH9KHUTQWA8Z92ZUTJCVQWPHE8LRHZQKL6WDGUB2CNDLCBZ_ejd.#=zGA1hXVHyGqZm3xpr1A==(IntPtr)
   at #=z4UN2rHjc_9fswkZz08YC6QokVjYbK6Q$$w==.#=zWiEmPiE=(Boolean)
   at #=z4UN2rHjc_9fswkZz08YC6QokVjYbK6Q$$w==.Finalize()
```

**Comment by wanjiaXG** [comment]
This issue is caused by the video background, this problem has been happening for many years. 
When playing multi, the first thing I do is check if the video background is turned off, as long as the video is closed, there will be no problem, and Storyboard will only make the loading speed slightly slower, with little impact.
In addition to crashing, there are also infinite loading issues, and multi will not be able to start after starting game.

I think it's similar to this issues.
https://github.com/ppy/osu-stable-issues/issues/1197

**Comment by peppy** [comment]
@arcutright could you provide logs when this happens next time?

also knowing which beatmaps cause the crash would be useful!

**Comment by arcutright** [comment]
> @arcutright could you provide logs when this happens next time?
> 
> also knowing which beatmaps cause the crash would be useful!

How can I provide useful logs? I have a copy of all the %localappdata%/osu! logs/, data/ files, and dlls from when this crash last occurred on cutting edge, but I didn't see any useful logs. The event viewer snippets above were the closest thing I found. If you'd like I have

```
network.log
performance.log
session.log
update_success.log
'osu!auth.log'
runtime.log
update.log
```

As for reproducing, I haven't found a pattern. I can usually reproduce the multi infinite-loading bug as mentioned in #1197 by doing `!mp abort` and then recreating the room and picking the same map, but a full game restart (close/open program) solves it for that map. With hard crashes, if it crashes on map X, after re-launching the game I haven't been able to reproduce the hard crash on the same map X.

**Comment by wanjiaXG** [comment]
There is a way to accelerate the reproduction of bugs. Assuming that the Songs folder has 100-200GB or even higher and the video function is enabled, it will be easy to reproduce these issues. You can even encounter problems when you first enter gameplay after starting osu!.
I have reduced the size of the Songs folder to 50GB in order to avoid the frequency of this issue, so I have to frequently download new maps, which also troubles me.
The fewer Songs folders there are, the harder it is to trigger those bug.

**Comment by Sargeanthost** [comment]
I also have this issue. I have video and the storyboards off.

Only happens when alt-tabbing. It has been going on for at least a couple of versions, not sure starting when. Event viewer of the two that happened today.

```
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Net.UnsafeNclNativeMethods+OSSOCK.recv(IntPtr, Byte*, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError ByRef)
   at System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32)
   at System.Net.FixedSizeReader.ReadPacket(Byte[], Int32, Int32)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.StartReading(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.TlsStream.Read(Byte[], Int32, Int32)
   at System.Net.PooledStream.Read(Byte[], Int32, Int32)
   at System.Net.Connection.SyncRead(System.Net.HttpWebRequest, Boolean, Boolean)
   at System.Net.ConnectStream.ProcessWriteCallDone(System.Net.ConnectionReturnResult)
   at System.Net.HttpWebRequest.CheckDeferredCallDone(System.Net.ConnectStream)
   at System.Net.HttpWebRequest.GetResponse()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zUVukhpwbF1ln()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zOdHQ8GMejSJd()
   at A.B.Z1(System.Object)
   at A.B.H1(System.Object)
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zc9AScD8=()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zQErXNwwwLBjc()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=znM$vleK0bLWVf_vDWG_Xgtmchj2gjV0QFI5iLb4=(System.Reflection.MethodBase, System.Object, System.Object[])
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=zVwoxKf$xdXY5y2y4MiXUdpY=(System.Reflection.MethodBase, System.Object, System.Object[], Boolean)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=z9Z0rByNnvSa83$ahc9BGwiA1oBv9elCT3mvsUoU=(System.Reflection.MethodBase, Boolean)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=zngV3waz1s84NF4H5apHEyEA=(#=qbuhFeljqqKxdHimbCy7ReAtz2ovZdZt$0$SRc4J2ODc=)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=za5jyoQ2SUWlOMvS9dNNSU$Q48JrL(#=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=, #=qbuhFeljqqKxdHimbCy7ReAtz2ovZdZt$0$SRc4J2ODc=)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=z_g2bLyvlwzpV1J7UN$8s7Uk=()
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=z9v6SU6BJ8S$q6TpwtG3ZX$4=(Boolean)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=zwbpACt$T3THoHbwyBXoblk$ArjuPASZgTPuLPWI=(System.Object[], System.Type[], System.Type[], System.Object[])
   at #=zMP3zBd1mUO9GahpnJ$C0$s0ipKI_toDeBIYdSUA=.#=zHdKR5SSGhzbB(System.Object, System.ComponentModel.DoWorkEventArgs)
   at System.ComponentModel.BackgroundWorker.OnDoWork(System.ComponentModel.DoWorkEventArgs)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(System.Object)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr, System.Object[], System.Object, System.Object[] ByRef)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessageSink)
   at System.Runtime.Remoting.Proxies.AgileAsyncWorkerItem.DoAsyncCall()
   at System.Runtime.Remoting.Proxies.AgileAsyncWorkerItem.ThreadPoolCallBack(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

This error was from earlier in the day when I also had another crash:

```
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Net.UnsafeNclNativeMethods+OSSOCK.recv(IntPtr, Byte*, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError ByRef)
   at System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32)
   at System.Net.FixedSizeReader.ReadPacket(Byte[], Int32, Int32)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.StartReading(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.TlsStream.Read(Byte[], Int32, Int32)
   at System.Net.PooledStream.Read(Byte[], Int32, Int32)
   at System.Net.Connection.SyncRead(System.Net.HttpWebRequest, Boolean, Boolean)
   at System.Net.ConnectStream.ProcessWriteCallDone(System.Net.ConnectionReturnResult)
   at System.Net.HttpWebRequest.CheckDeferredCallDone(System.Net.ConnectStream)
   at System.Net.HttpWebRequest.GetResponse()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zUVukhpwbF1ln()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zOdHQ8GMejSJd()
   at A.B.Z1(System.Object)
   at A.B.H1(System.Object)
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zc9AScD8=()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zQErXNwwwLBjc()
   at #=zcfYyoBe8EckczyEekP0Ba18=.#=zbzPF50A=(Boolean)
   at #=zcfYyoBe8EckczyEekP0Ba18=.#=z3JbHjCk=()
   at #=zfhjrwbOJApcpofg2Mg==+#=zkSz_Rs6a59wk6hWRc_eB6Ug=.#=z2hiXcuqqLm$GiJbeCw8NFPI=()
   at #=zgfRPpNH4DVouVPcew_6nKViriDp4+#=z9m5LMsoXUiDokt1JpDPEFvk=.#=zEHdfO5Em7_NMlEkuWg==(System.Object)
   at #=z0As3f94NGz3iUzJ5Uz9uwPU=.#=z0iCbFCHEYIxi()
   at #=z0As3f94NGz3iUzJ5Uz9uwPU=.#=z0Ns5mZs=()
   at #=zVpSSamIGON7UpICsMgioHtA=.#=z0iCbFCHEYIxi(#=z0As3f94NGz3iUzJ5Uz9uwPU=)
   at #=zVpSSamIGON7UpICsMgioHtA=.#=zwIETPO7J8hXy()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```


Here are the dates for when osu has crashed for this security violation, not sure if it will help:

4/15 4/19 4/19 4/23 4/28 5/1 5/1 5/16 5/17 5/17 

I'm on mobile  but you can see the logs from the other issue I made: https://github.com/ppy/osu/issues/28199#issue-2303856598

**Comment by Someone999** [comment]
These bugs can relate to the pointer allocation in osu! .  I'm discussing the bug with the official developers now.
Sometimes, an invalid pointer can be allocated which will result in crashes.
