### ISSUE TITLE
Crash when switching maps of different modes

### ISSUE THREAD

**Issue by milaneyia** [ppy/osu-stable-issues#137]
If you use the Difficulty Selection box (ctrl+shift+o in the editor) in a set with maps of different modes, the game will crash if you switch between a map from a mode to another map of another mode.
For example, in this set https://osu.ppy.sh/beatmapsets/1033323#osu/2160450 you switch from an standard map to a taiko map, the game crashes.

It didn't happened before the new updates.

Log from peppi

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at #=zK2rC0UIZ7Qag1vmn9RpidK3rD7ZJ.#=zAFSPdcs=(Boolean #=zbA4nirPJ9o0o)
>    at #=zK2rC0UIZ7Qag1vmn9RpidK3rD7ZJ.#=zhGHbazA1FWWv()
>    at #=zDoho2qc_cC8J1kcH9PiwyAA8zQ$7.#=zOvnWpOw=(#=zFbbyR3dkk5Pp6WGuXanqHnBqQUDpg6GCQp8BhDc8vf64 #=zm9dGhh$v$aB$, Boolean #=zNxjLqwHoBU1j, Boolean #=zTJZtXaju_110)
>    at #=zeoeRzHrzviFNiX4tqLkLwhZJwc0lg7Sjlw==.#=zjcZvqar_$A4eY4XMmg==(Object #=zrBb6VZ0=, EventArgs #=zOSgAWQ4=)
>    at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
>    at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
>    at System.Windows.Forms.ListBox.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by peppy** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
at osu.GameplayElements.HitObjectManager.Load(Boolean processHeaders)
at osu.GameplayElements.HitObjectManager.LoadWithEvents()
at osu.GameModes.Edit.Editor.LoadFile(osu.GameplayElements.Beatmaps.Beatmap beatmap, Boolean warnOnLostChanges, Boolean clearCache)
at osu.GameModes.Edit.Forms.OpenDialog.listBox1_SelectedIndexChanged(Object sender, EventArgs e)
at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
at System.Windows.Forms.ListBox.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
