### ISSUE TITLE
osu! crashes when creating new difficulty on beatmap after last CE update

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#188]
I was told to create an issue here for the bug i have.

After the last Cutting Edge Update from Oct, 27th (Build 20191027) my osu! crashes whenever i try to create a new difficulty on one of my unsubmitted beatmaps. 
The thumbnail of the beatmap is also bugged and shows the background of a completely different beatmap for me. 
Screenshot of the Beatmap + Thumbnail: https://i.imgur.com/CYw7skv.jpg

The Error Code i get when osu! crashes is following: 
`System.NullReferenceException: Object reference not set to an instance of an object.
   at #=zXYCeZRaYegZcGNxlqGYjL4M7Mpay.#=zn$eNG7o=(#=ziIX16_1DKHzxplgRy58zIwaq4Tms #=zJhxmBFE=, StringWriter #=zvPMYHYY=)
   at #=zXYCeZRaYegZcGNxlqGYjL4M7Mpay.#=zq6UPNHs=(StringWriter #=zvPMYHYY=, Boolean #=zVUjs$K5jDB2d6qyUhQ==)
   at #=zXYCeZRaYegZcGNxlqGYjL4M7Mpay.#=znmyfczs=(Boolean #=z$w6HAnCIcYH9, Boolean #=z3qSXoSo=, Boolean #=z3CnaUYOhZQJF, Boolean #=zrRaSeAIvSrTi)
   at #=zcoyhrD4ie5i5cdxdpJDLpqVe_rwkujvdzg==.#=zKxCFgqfqUpkM(Object #=zG2_yTxo=, EventArgs #=zJhxmBFE=)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

This is not the only beatmap where the thumbnail broke. There are some more, but i noticed this only happened on unsubmitted beatmaps.

I also wanted to add an .osz of the beatmap where it happened.. but.. osu! crashes even when i try to Export the beatmap. So i just send a .rar of the beatmap folder. 
Link of the beatmap folder: [Click](https://www.dropbox.com/s/zojdu9czsb5ti35/Fuki%20-%20DO%20NOT%20LOGOUT%21.rar?dl=0)

I tried to fix the thumbnail thing with deleting the osu!.db data in the folder, which made all beatmaps reload after starting osu!, but it didn't help. 

So yeah, not sure what exactly causes this error. Maybe something with the last CE Update?

**Comment by peppy** [comment]
Thanks for the report. Fixed in next release.
