### ISSUE TITLE
osu! crashes when trying to type in the search box in multiplayer

### ISSUE THREAD

**Issue by Trosk** [ppy/osu-stable-issues#201]
As mentioned in the title, osu! currently crashes when trying to type in the search box in multiplayer (when trying to find a specific lobby). Happens on all 3 release streams.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at #=zQco9ZRJjs5XewrXD2nO8bD2bZ$ll.#=zm2W4QjY2F8Lb(#=zS7TqaDxozfoigCgy$4v9J95gnhBJLQDA5Q== #=zXPft0Bk=)
   at #=zQco9ZRJjs5XewrXD2nO8bD2bZ$ll.#=z5DZUj9k=()
   at #=zRmQcE32N39oA3iUlDQ==.#=z7lsK7vk=.#=zSSsut0BVJZ8JGBbhyw==(#=zAbHhkOUFkKjqoGdv7$uM_M0= #=zfVRmG7g=)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at #=zRmQcE32N39oA3iUlDQ==.#=zfxqRIHg07XDcWb2NtA==()
   at #=z0gzQj8NIzzIwrsV$RA==.#=zOEwQAOs=(#=zGYq6s2HjmtQ$xz5nw6fI3_U= #=zN4dUTxI=)
   at #=zRmQcE32N39oA3iUlDQ==.#=z5DZUj9k=()
   at #=zeOcjtwOY13Ka9tcl1A==.#=zf_xsQks7q5ke(Object #=zl269dMc=, EventArgs #=zZEnNPU0=)
   at #=z5tcg4oAizLn5cNJO8gcCc8c=.#=zCuUMcp8=(Object #=zl269dMc=, EventArgs #=zp6QbxYk=)
   at #=zTi9$$1gvGou4597SGEy_Edk=.#=zBBdbkwzmldO54d_aSA==(Object #=zl269dMc=, EventArgs #=zZEnNPU0=)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at #=zTi9$$1gvGou4597SGEy_Edk=.#=zVDMV7wU=()
   at #=zeOcjtwOY13Ka9tcl1A==.#=zVDMV7wU=()
   at #=zg$xAUCJqX$wdSvSZqA==.#=z9IX5Hu9tdOzm(String #=zVeP14459fX7C, Boolean #=zgZXMKUp0_a6slDZwrIJJl7M=, Boolean #=zT7qyKrY2niuDHalaGQ==)
```

**Comment by peppy** [comment]
Added protection against this in next release!
