### ISSUE TITLE
Crash when moving cursor too quickly on wine

### ISSUE THREAD

**Issue by WebFreak001** [ppy/osu-stable-issues#284]
Since a few days ago osu! has continuously been crashing every time I moved my mouse faster than a few pixels per frame. This issue just suddenly started happening. At first it was fine for an hour or two after restarting osu! 4-5 times but now even after restarting osu! 30 times it doesn't seem to go away anymore. It happens when moving too quickly with either tablet or mouse. When not moving at all or just moving very slowly I can easily navigate around all the menus, change settings and start maps, but once I start to move it quicker it seems to crash osu!

Video recording of this issue:

https://wfr.moe/f6caui/crash.mp4 (20 MiB)

Stacktrace:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at #=zhWiGd$DXGgRK4EbSve2508Ev50bfXBJxGkPSG2g=.#=zMHObixn7vfEI(Int32[] #=zS8kimwo=, Single #=zAcK6lFVy4nDR)
   at #=zhWiGd$DXGgRK4EbSve2508Ev50bfXBJxGkPSG2g=.#=z3hOiQ$8=()
   at #=zGp8t0fBbys4CQ2efpQ==.#=z3hOiQ$8=()
   at #=zNIxULleMPHR2ZwOePg==.#=zZDwD4WKmNnuJ(Object #=zR5isklE=, EventArgs #=zaPa_BJs=)
   at #=zTWRuOiFOcJSBF$ipd36Gzf8=.#=zJf0JhR0=(Object #=zR5isklE=, EventArgs #=zRQwnBEc=)
   at #=zBbucSSoldPUJ_sTJD9_JEWM=.#=ziE0uSzSqbL9xZcAUgw==(Object #=zR5isklE=, EventArgs #=zaPa_BJs=)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at #=zBbucSSoldPUJ_sTJD9_JEWM=.#=zazcmPj4=()
   at #=zNIxULleMPHR2ZwOePg==.#=zazcmPj4=()
   at #=zNKtgfpFWi7zOKnoGXg==.#=zrbTBobM47uUh(String #=z6Vkw8ISdhDcg, Boolean #=z7fkNddzOp4B_fcK_NWppDlE=, Boolean #=zvXwGyahLuIAbf7M_oQ==)
```

System:
wine-5.0-rc2 (Staging), reproduced with Windows Version set to Windows XP, Windows 7 and Windows 10 (usually selected Windows XP before)
ArchLinux with kernel 5.2.0-rc3-git (commit g4998f1efd190)
CPU: AMD Ryzen 7 1700X
GPU: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.32.0, 5.2.0-rc3-git-00026-g4998f1efd190, LLVM 9.0.0)
OpenGL: 4.5 (Core Profile) Mesa 19.3.1

(also happens on non-staging wine of same version)

osu! version: reproduced on Stable and Cutting Edge 20191225.1, Stacktrace from Cutting Edge

I think this might be an issue with some things I tweaked over the days (switch to linux compiled from git to fix huion drivers, wine update, osu update or other things)

However because the stacktrace is obfuscated I have no way of knowing what is breaking here and if I could fix it myself and what even causes this.

**Comment by peppy** [comment]
I unfortunately have no idea how the underlying code works. Since it hasn't broken on supported platforms I'm unable to fix this unless you can reproduce on windows.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at osu.Graphics.Renderers.CursorTrailRenderer.findRanges(Int32[] ranges, Single alphaThreshold)
   at osu.Graphics.Renderers.CursorTrailRenderer.Update()
```

If it's not an actual bug at our side it looks like you may have broken basic arithmetic of your system.

**Comment by WebFreak001** [comment]
ok yes this seems to be a wine update causing this, tried in 4.21 (still happening) but then in 4.1 where it didn't happen anymore. I will check for the commit which introduced this and report this to the wine devs.

Thanks for the response hinting I broke basic arithmetic of my system lol.
