### ISSUE TITLE
Editor Crash

### ISSUE THREAD

**Issue by JDECOMBE** [ppy/osu-stable-issues#413]
Hi,

Osu! just randomly crashed while opening the editor for this map only (https://osu.ppy.sh/beatmapsets/1116349#osu/2332088). It looks like any other map is fine.
This is what I did: Go to beatmap > F3 > Edit > Black screen for 2/3s then osu! closes.
Here are the logs from the Windows' Event Viewer:
```
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Platform.Windows.Functions.SwapBuffers(IntPtr)
   at OpenTK.Platform.Windows.WinGLContext.SwapBuffers()
   at OpenTK.Graphics.GraphicsContext.SwapBuffers()
   at #=zfdq4mRPRER3LiCp1qrYoRZk=.#=z1BcOjMFbPoLL()
   at #=zgF5lndvtXST5Jky1Osj01jQuk25P.#=z1BcOjMFbPoLL()
   at #=zOwH6k5vR7JpRdp$OGQ==.#=zHcSF7BU=()
   at #=z8PAcaRQuFLHrz90zpA==.#=zBWgnwLZfkwiN(System.Object, System.EventArgs)
   at #=zsYC3REew_WeRkvPHW60OCHQ=.#=zWbbqoEw=(System.Object, System.EventArgs)
   at #=zV0qjJ6kIC2u2BYY7_GsaeUU=.#=zNQiNqpMr6rWMB3g6ng==(System.Object, System.EventArgs)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at #=zV0qjJ6kIC2u2BYY7_GsaeUU=.#=zJ$OQ_80=()
   at #=z8PAcaRQuFLHrz90zpA==.#=zJ$OQ_80=()
   at #=znEjmn$ghy7MB5$dGqA==.#=zaTahEecpvTTu(System.String, Boolean, Boolean)
   at #=znEjmn$ghy7MB5$dGqA==.#=znOkOu6w=(System.String[])
   at #=znEjmn$ghy7MB5$dGqA==.#=zRnBPCno=()
   at #=qI2ofbMH8PfcIW1ajY8UFmHPCXttEP_S73z86ZNQ2GFo=.#=zeTPzJdI=()
```

I hope this is helpful somehow !

**Comment by peppy** [comment]
That sounds like something at a driver level. Can't repro it here.
