### ISSUE TITLE
Endless SR calculation when switching mods

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-stable-issues#449]
Everytime I change mods in song select, the "beatmap diffcalc is running in background" notification appears. But only the two first times, it seems.

[YouTube Demo](https://youtu.be/9XzaKitwM_0) (dont mind the stretch lol)
[Logs.zip](https://github.com/ppy/osu-stable-issues/files/4580048/Logs.zip)

**Comment by peppy** [comment]
Is this still occurring? We've since fixed a few issues causing certain beatmaps to process forever.

**Comment by ThePooN** [comment]
It is still occuring.

**Comment by peppy** [comment]
Do you happen to have logs? If on cutting edge, the logs should help identify which beatmap it's getting stuck on if any.

**Comment by ThePooN** [comment]
[runtime.log](https://github.com/ppy/osu-stable-issues/files/4906620/runtime.log)

**Comment by smoogipoo** [comment]
Please post your osu!.db.

**Comment by ThePooN** [comment]
I do not remember it being 54.8MB before... [osu!.db.zip](https://github.com/ppy/osu-stable-issues/files/4906852/osu.db.zip)

**Comment by smoogipoo** [comment]
Does this only happen in mania?

**Comment by ThePooN** [comment]
Nope, I have only been playing standard in the last 2 days.

**Comment by smoogipoo** [comment]
Hmm... One potential issue could be `Apocalyptica_-_Prologue_Apprehension`, could you paste it here for further inspection? (And maybe try deleting it after doing so to see if it fixes it)

**Comment by smoogipoo** [comment]
The other one (which is displayed in the logs) is https://osu.ppy.sh/beatmapsets/490411#taiko/1229703, maybe post that one too - perhaps you have a different version because I can't replicate with a fresh download.

**Comment by ThePooN** [comment]
> Hmm... One potential issue could be `Apocalyptica_-_Prologue_Apprehension`, could you paste it here for further inspection? (And maybe try deleting it after doing so to see if it fixes it)

[Apocalyptica - Prologue (Apprehension).osk.zip](https://github.com/ppy/osu-stable-issues/files/4907129/Apocalyptica.-.Prologue.Apprehension.osk.zip)

> The other one (which is displayed in the logs) is https://osu.ppy.sh/beatmapsets/490411 (the entire set), maybe post that one too - perhaps you have a different version because I can't replicate with a fresh download.

Selecting some of the difficulties of this set in Song Select made my game process all my beatmaps like 10 times.

After having successfully opened one of them in the editor, this error happened while trying to export:
```
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at #=zegEXgkZbJ5MCZib1zVUEbD_Rvq03.#=zw6dhNPg=(String #=zJKuBh9s=)
   at #=zBtE9DPHUz5wRookcOVp0bCn_wGHIu$eueA==.#=zKZTXCI20xVYP(String #=zVm$81b4=, Boolean #=zWFyA5fk=)
   at #=zmdNPUhGwPB1_tYpt298tLLgqRg6V5GroOw==.#=zClV8X1Y=(Stream #=zK6cyjNV2X_4A, String #=zZqcfA45ywxXr, Boolean #=zWFyA5fk=, String #=zIFhAKDdHYLSq, String #=zjvMbA$R8rJ4i)
   at #=zszRonafhbxwJ32dxDA==.#=zWMI_UAY=(String #=zfsNmy84=, String #=z98P9DOMXM4K$)
   at #=zZsfJIzZHKQsuvPfX3K27F1kSJlJ6.#=zc9LCls2EBCKA()
   at #=zioij4flF42qgBBNrTYQWQTejePdq2Er86w==.#=znIdTTqeDsNzQ5AgZwvldYuY=(Object #=ze$FHWJ0=, EventArgs #=zpdg55sM=)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```


Anyway, I'm not sure what osu! did to my Songs folder with all that reprocessing and beatmap exporting, so here are the two sets exported from my torrents mappack of May 23rd 2020. Note that for some reason, https://osu.ppy.sh/beatmapsets/490411 seems to be split in two folders. 
[smoogi-package.zip](https://github.com/ppy/osu-stable-issues/files/4907167/smoogi-package.zip)

**Comment by smoogipoo** [comment]
What's going on here is that that beatmap's folder + file names are too long and stable's throwing a fit trying to descend into the directory (exceeds Windows' max path length).

Given how rare of a situation this is, I think the best solution for now is to delete the beatmap locally...

**Comment by ThePooN** [comment]
Oh, I did this under Wine.

That situation might not even be reproducible on Windows, considering it's an issue caused by the host OS/filesystem.
