### ISSUE TITLE
Crash while scrolling through usercards

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#584]
Version:  b20201102.3cuttingedge

I was gradually scrolling from the end to beginning with all osu! gamemode usercards displaying while in main menu (with osu! cookie)

Crash log:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at #=zWvWHP5ezBbLaH9CSw1lmarRUZ7YqTjISAIcszVE=.#=z8wgdkyBvuoJn()
   at #=zIB_CP7YDfuhjj$gXZQ==.#=ziN22Mmw=()
   at #=zRrL_4ArUyhx6adlwJQ==.#=z4zpUFViS2FK$(Object #=zWaVELkQ=, EventArgs #=zeFNNnxc=)
   at #=zQK5ap3mraoN1iuBUDXKg$Q0=.#=z8pypVVk=(Object #=zWaVELkQ=, EventArgs #=zO6mXjH8=)
   at #=zpHCaJ1Fx$tDBSk0b1bcNXGg=.#=z3XJ_83Yk_mIT5zypkw==(Object #=zWaVELkQ=, EventArgs #=zeFNNnxc=)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at #=zpHCaJ1Fx$tDBSk0b1bcNXGg=.#=zYKN0FTs=()
   at #=zRrL_4ArUyhx6adlwJQ==.#=zYKN0FTs=()
   at #=z$MY0V$JKu6tYzxoLAg==.#=zo8ZY625BqLbw(String #=zmOiIcnUd$$aA, Boolean #=zNXn_cOfsspxaWlSMSo1WT2I=, Boolean #=zR_NVeSrpYDy5YVBNDA==)
```

**Comment by peppy** [comment]
Should be fixed in the next release.
