### ISSUE TITLE
osu!mania editor crash when attempted to place note before first timing point

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-stable-issues#614]
Where I tried placing note:

![](https://i.imgur.com/A1y9KiZ.png)

I was able to replicate it every time I tried. NM difficulty. [Link to osz](https://drive.google.com/uc?id=1wbnZ04vNhBz-RsjT68CBmoFD0XQ4UEgb)

crash log:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at #=zbgvM1zE5IGRCbderWLvxCo3rhXiE9mVIAqQfsdVJf4oq.#=zrQVxNmD$bsau()
   at #=z1ZawXizB_Iv_hilMgx2QsA97cBXc.#=zrQVxNmD$bsau()
   at #=z1ZawXizB_Iv_hilMgx2QsA97cBXc.#=ztVWyXvI=()
   at #=z3K$B748O9CHfhL6_rg==.#=zuCdiNdg=.#=zyZpw$PryoQm1QDaNlAbhyro=(#=z7q24Jobb9nM1exU6mrWXfz0= #=zgvSmwjs=)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at #=z3K$B748O9CHfhL6_rg==.#=ztVWyXvI=()
   at #=zNEbImeExrHjZ5p$v0Q==.#=zb1aa_yiugjWX(Object #=zvvhLuco=, EventArgs #=zjqkdWkk=)
   at #=zfLYYminmM8dls3pHmCNGcFY=.#=zuZ2C$Jo=(Object #=zvvhLuco=, EventArgs #=zIvT3VOA=)
   at #=zABkgv850AsdgPSPOgS2zLxw=.#=zn_aG10bSyY9vn4QJEw==(Object #=zvvhLuco=, EventArgs #=zjqkdWkk=)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at #=zABkgv850AsdgPSPOgS2zLxw=.#=zh9uPdIA=()
   at #=zNEbImeExrHjZ5p$v0Q==.#=zh9uPdIA=()
   at #=zDKLBpt_AxfZN1VWSyQ==.#=zHmduVwdJ567v(String #=z9T$JAIaQ45Ff, Boolean #=zxcwPDjhaAhMM_Nss6GfXiUI=, Boolean #=ztwcQ0EguWZ0iLjC8Lw==)
```

**Comment by peppy** [comment]
I've fixed this crash. Note that placing objects before the first timing section is generally not supported, and while it won't crash any more, the behaviour may be unexpected (in testing i noticed that some hitobjects of this nature would be discarded on save).
