### ISSUE TITLE
Osu Crashed

### ISSUE THREAD

**Issue by Kawaii-Miku** [ppy/osu-stable-issues#661]
I got this crash issue 

System.NullReferenceException: Object reference not set to an instance of an object.
   at #=zrplfimj2kiFotwj5DX50q_k=.#=zXzk8SAV0ISVTeSV53w==(Object #=zHiJ2mTA=, EventArgs #=zGFMB6QI=)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Sebola3461** [comment]
Submit the map that made your game crash
