### ISSUE TITLE
Osu! crashes when you create a new inherited point while placing a slider.

### ISSUE THREAD

**Issue by OneShotFox** [ppy/osu-stable-issues#755]
The title says it all pretty much.

While using the editor, If you change the slider velocity in the timing and control points panel while being in the middle of placing a slider (the point where you can place slider nodes and anchors) and then accept that change, Osu asks you to save the map and then crashes fully without fail.

Crash report Screenshot: https://prnt.sc/132aag3
Bug Found on Stable 20210423.2 in the editor

**Comment by peppy** [comment]
Thanks for a screenshot of text. Please copy the text and paste it here so we can actually act on it.

**Comment by OneShotFox** [comment]
Here:
```
System.InvalidCastException: Unable to cast object of type '#=zx5kRnTyPCznK9yqt4mZM1vjL8vfKMfSziV0jhVtva7lU' to type '#=zu6lDjMu2wmrFne79VQ=='.
   at #=zu6lDjMu2wmrFne79VQ==.Equals(Object #=zBZ4_1ms=)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.List`1.Contains(T item)
   at #=zhWJUPNfxHF45oILnAJ7NPz2$Cs1x.#=zIRGQnsQ=(Object #=zBZ4_1ms=)
   at #=zhWJUPNfxHF45oILnAJ7NPz2$Cs1x.#=z0Hjp_ZDlmY7m[T](List`1 #=zqB0cduc=)
   at #=zhWJUPNfxHF45oILnAJ7NPz2$Cs1x.#=zhC$R6JY=[T](List`1 #=zqB0cduc=, #=zChty$0suEC_AOYRkEn$nUXt6JAty #=zh3O6b7s=)
   at #=zHQW6SfkIBfoUEMoDwmn$2h9DsHNFGXhvrQ==.#=zhC$R6JY=[T](List`1 #=zqB0cduc=, #=zChty$0suEC_AOYRkEn$nUXt6JAty #=zt12MvxQ=)
   at #=z9pFq0OaNa3ZeUQZl_C2GKuHAcacMh6tqlg==.#=zhC$R6JY=[T](List`1 #=zqB0cduc=, #=zChty$0suEC_AOYRkEn$nUXt6JAty #=zt12MvxQ=, Boolean #=zqeg$AVw=)
   at #=zWEocMigzCuzF_HSy7ASl3xT_I6cS.#=zuou4eRB0uvq_MubvWQ==(Boolean #=zNvqLkaE=)
   at #=zAbfhti95IJQ5TAHpzZcRlCtRr1lXnAxcqg==.#=zN8$YUwW7Zl8943nm2Q==(Object #=z_CcQdRI=, FormClosingEventArgs #=zB0pZOvg=)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

```

**Comment by peppy** [comment]
Sounds like a feasible solution for this would be to end slider placement when opening a dialog, yes?

**Comment by peppy** [comment]
This should be resolved in the next cutting edge release.
