### ISSUE TITLE
Can't Import new Tracks

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu-stable-issues#86]
osu! crashes when importing a new track then hitting OK in Song Setup.

![image](https://user-images.githubusercontent.com/20495991/65367433-1f363f80-dc64-11e9-9100-1fdd8f2dc08a.png)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at #=zp1sZppEUiUWs$7bdX57eiW2QwS_euOMmbQ==.#=z1vCGYIfNNAXO(Object #=zZOydXs8=, EventArgs #=z$VceB$c=)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

version: b20190921.1cuttingedge

**Comment by smoogipoo** [comment]
Fixed in the next cutting edge release.
