### ISSUE TITLE
Tournament client breaking with > and < characters within team names

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-stable-issues#893]
I haven't yet confirmed that this is an actual issue (on a quick look I can't see anything causing this).

Originally posted in https://osu.ppy.sh/community/forums/topics/1470936?n=1

> When you create a mp lobby containing the character "<" within brackets constraining team names, joining the lobby with the tournament client will not display the chat despite being addreffed (like a validation/code injection bug). Selecting these rooms will also incur a delay on the client much longer than regular lobbies without these characters. Other functionality such as displayed team names and scoring (best of 9 being treated as a best of 7) also seem to break inconsistently.
>
> ![](https://i.ppy.sh/1505fc00e59bf8804875e33ea24502ff8b9c9c9e/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3730373934323130333233333036393135362f3931343137313236303736303634393733382f756e6b6e6f776e2e706e67)
>
> Sample: https://osu.ppy.sh/community/matches/94509941

**Comment by omkelderman** [comment]
Made a quick video showcasing the problem:
https://youtu.be/OdWb9dTJn6E

logs of that session from the video:
[Logs.zip](https://github.com/ppy/osu-stable-issues/files/7613139/Logs.zip)

didnt test setting BO, just noticed that was originally also mentioned, oh well

**Comment by peppy** [comment]
Thanks a lot for the repro and logs. Makes sense why this is happening - it's hitting an exception midway through updating the flags, as `<` is not valid in windows filenames.

Relevant part of logs:
```csharp

2021-11-28T09:14:40: ERROR: soft handled
2021-11-28T09:14:40: System.ArgumentException: Illegal characters in path.
2021-11-28T09:14:40: at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
2021-11-28T09:14:40: at System.IO.Path.Combine(String path1, String path2)
2021-11-28T09:14:40: at #=z85R9M2OF8gFY1E0GhTXH8lx2c9ZMtUxsohFOWkU=.#=zCoZSyCs=(String #=zHkZAsbQ=)
2021-11-28T09:14:40: at #=zbf4KGbNWHl9vzwWUqTA$HtJiQwBlmY$wWfB4lUzFiur1g5FT8Q==.#=z1klRcJE=(String #=zgs_Wq$Y=, String #=z4fR5rO0=)
2021-11-28T09:14:40: at #=z$BVmKRPjD52Krn$rc5EuAyjavzDZbcbe9oSGBD8yq2PoBb1D_cvi0OVgeGXu.#=zMKQHJg8=(Object #=zkQs50jQ=, EventArgs #=zySMPzOs=)
2021-11-28T09:14:40: at #=z0U9KVsPuD0PvSZZ2$4GLMOw1yaPj.#=zG3yzIIU=(Boolean #=zI6mG4pSDVX8_D1mZcQ==)
2021-11-28T09:14:40: at #=zrU0sxQg4uAMbZ6JA_1VgVAWXWqag2KjLEA==.#=z4TVciZhNEalJ(Boolean #=z9Hz0QLU=)
2021-11-28T09:14:40: at #=zrU0sxQg4uAMbZ6JA_1VgVAWXWqag2KjLEA==.#=zPBPHubtNd7Hz(Boolean #=z9Hz0QLU=)
2021-11-28T09:14:40: at #=ziwcDxzHt1hnXZDFq9ZNjj60=.#=zJdANo7YdtcN5()
2021-11-28T09:14:40: at #=zRoj6hGv$QosrXHyeqg==.#=zh8CUAj8=(#=zlCv6hfwC$61egugrRn6FDwE= #=zRQPfOKw=)
2021-11-28T09:14:40: at #=zN85xLp7reoMH_O6x7w==.#=z0LyYrpI=()
```

**Comment by smoogipoo** [comment]
Fixed in the next release.
