### ISSUE TITLE
Osu can't create files

### ISSUE THREAD

**Issue by ghost** [ppy/osu-stable-issues#907]
./osu.AppImage
cp: cannot create regular file '/home/r1413/.cache/thumbnails/large/e4adfe28f6aad254bbf4ca8bc9723490.png': No such file or directory
touch: cannot touch '/home/r1413/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
Unhandled exception. System.InvalidOperationException: couldn't retrieve valid display mode
   at osu.Framework.Platform.SDL2DesktopWindow.getClosestDisplayMode(Size size, Int32 refreshRate, Int32 displayIndex)
   at osu.Framework.Platform.SDL2DesktopWindow.updateWindowStateAndSize()
   at osu.Framework.Platform.SDL2DesktopWindow.updateWindowSpecifics()
   at osu.Framework.Platform.SDL2DesktopWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Desktop/Program.cs:line 104

**Comment by peppy** [comment]
looks like you are running lazer? in which case you're reporting this in the wrong place. also it's not failing on the "can't create files" but the "can't retrieve valid display mode".

ie. your system is probably not setup properly. it's linux so this is your responsibility. likely gpu drivers or otherwise.
