### ISSUE TITLE
osu! updater: An error occured! Please check your internet connection!

### ISSUE THREAD

**Issue by melcone** [ppy/osu-stable-issues#960]
I installed osu on manjaro using lutris. The installation went fine, but this happened:
![image](https://user-images.githubusercontent.com/98726565/158976677-8f4c309a-148b-4be8-adb1-ddebf2b133f3.png)
update.log:
>2022-03-18T09:18:12: CallbackStatus updated to Checking
2022-03-18T09:18:12: 
2022-03-18T09:18:12: Beginning update thread
2022-03-18T09:18:12: Stream: Stable40
2022-03-18T09:18:12: 
2022-03-18T09:18:12: Running cleanup..
2022-03-18T09:18:12: Cleanup successful!
2022-03-18T09:18:12: Requesting update information...
2022-03-18T09:18:16: System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.NotSupportedException: The requested security package is not supported.
2022-03-18T09:18:16: at System.Net.SSPIWrapper.GetVerifyPackageInfo(SSPIInterface secModule, String packageName, Boolean throwIfMissing)
2022-03-18T09:18:16: at System.Net.Security.SecureChannel..ctor(String hostname, Boolean serverMode, SchProtocols protocolFlags, X509Certificate serverCertificate, X509CertificateCollection clientCertificates, Boolean remoteCertRequired, Boolean checkCertName, Boolean checkCertRevocationStatus, EncryptionPolicy encryptionPolicy, LocalCertSelectionCallback certSelectionDelegate)
2022-03-18T09:18:16: at System.Net.Security.SslState.ValidateCreateContext(Boolean isServer, String targetHost, SslProtocols enabledSslProtocols, X509Certificate serverCertificate, X509CertificateCollection clientCertificates, Boolean remoteCertRequired, Boolean checkCertRevocationStatus, Boolean checkCertName)
2022-03-18T09:18:16: at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
2022-03-18T09:18:16: at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
2022-03-18T09:18:16: at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
2022-03-18T09:18:16: at System.Net.ConnectStream.WriteHeaders(Boolean async)
2022-03-18T09:18:16: --- End of inner exception stack trace ---
2022-03-18T09:18:16: at #=z7u$tXk7zg3MRP4rO9qsxqy0=.#=zz5IVwHGOMZ$T()
2022-03-18T09:18:16: at #=zrBZfk3ZPdHbjDTCv_Ck5h5I=.#=zZkeJkz0=()
2022-03-18T09:18:16: 
2022-03-18T09:18:16: Saving out global config
2022-03-18T09:18:16: 
2022-03-18T09:18:16: Ending update thread with result: Error
2022-03-18T09:18:16: 
2022-03-18T09:18:16: CallbackStatus updated to Error
2022-03-18T09:18:16: Running cleanup..
2022-03-18T09:18:16: Cleanup successful!
2022-03-18T09:18:16: Resetting update process

**Comment by peppy** [comment]
We can't support linux as an operating system for this version of osu!, sorry.

Please open an issue with lutris, or consider using [lazer](https://github.com/ppy/osu#running-osu) instead (which supports linux).
